export const PARAMETERS = {
    USERNAME_MIN_LENGTH: 1,
    USERNAME_MAX_LENGTH: 16,
    NAME_MIN_LENGTH: 1,
    NAME_MAX_LENGTH: 16,
    PASSWORD_MIN_LENGTH: 3,
    PASSWORD_MAX_LENGTH: 30,
    POST_CONTENT_MAX_LENGTH: 500,
    POST_IMAGES_MAX_LENGTH: 4,
    BIO_MAX_LENGTH: 500,
    LOCATION_MAX_LENGTH: 16,
    LINK_MAX_LENGTH: 100
}